version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: user_activity_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  producer-service:
    build: ./producer-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer-service:
    build: ./consumer-service
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy